// Generated by CoffeeScript 1.6.3
(function() {
  var express, http, port, server;

  express = require("express");

  http = require("http");

  port = process.env.PORT || 8001;

  server = module.exports = express();

  server.configure(function() {
    server.use(express["static"](__dirname + '/../public'));
    server.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
    server.use(express.bodyParser());
    server.use(server.router);
  });

  http.createServer(server).listen(port);

  console.log('Welcome to Backbone-Require-Boilerplate!\n\nPlease go to http://localhost:' + port + ' to start using Require.js and Backbone.js');

}).call(this);
